### ISSUE TITLE
Features or improvements

### ISSUE THREAD

**Issue by CMACKINTOSH75** [MattiasC85/Send-CMMessage#1]
I really like your script it achieves something i need in my project but i would like to know how to extend it.

How can i sent different Message ID rather than 39997

https://docs.microsoft.com/en-us/sccm/develop/reference/core/servers/manage/sms_statusmessage-server-wmi-class

Ideally i would like to send these

39997 | RaiseInformationalStatusMsg Method in Class SMS_StatusMessage
39998 | RaiseWarningStatusMsg Method in Class SMS_StatusMessage
39999 | RaiseErrorStatusMsg Method in Class SMS_StatusMessage

Have you managed to get further on this project, the blog post is old but it looks like there are recent commits.

Cant believe that this type of function isnt natively in SCCM.

thanks

**Comment by MattiasC85** [comment]
Wow, first of all. A big sorry for not answering earlier. Havn't even seen that an issue had been open until this very now.
I think what you're looking for is the $SMS_MessageID parameter, have you tried that?
