### ISSUE TITLE
Severity

### ISSUE THREAD

**Issue by CMACKINTOSH75** [MattiasC85/Send-CMMessage#2]
Also how is it possible to get severity levels changed

i tried 1 and 2 and nothing changes it still shows as informational

i added severity as a parameter

**Comment by CMACKINTOSH75** [comment]
I have discovered using WMI that using the following message IDs work
ERROR       3221265471
WARNING 2147523646
INFO          1073781821

**Comment by MattiasC85** [comment]
Would this cover what you want to do? :)
![ErrorWarnInfo](https://user-images.githubusercontent.com/44426149/76038766-c6750d80-5f4a-11ea-86c1-06140c1e6c93.png)

**Comment by CMACKINTOSH75** [comment]
Hi

Thanks i was able to get this working with the different levels like
warning and error and information.

I see you did a post update on this topic.

Thanks for your work, it helped me a lot.

Chris

**Comment by MattiasC85** [comment]
You're very welcome. Glad you gave me some feedback. Hard to improve things if I don't know what's missing. 👍
